# Generated by Django 5.1 on 2024-08-26 01:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lms_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='states',
            new_name='status',
        ),
    ]
